name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: pull-request :
    types : [labeled]
jobs : 
  docker : 
    runs-on : ubuntu-latest
    steps :
      working-directory : ./web
        - uses: actions/checkout@v3
        - name: Build the Docker image
        run: docker build . --file Dockerfile --tag webImage:$(date +%s)
      working-directory : ./db
        - uses: actions/checkout@v3
        - name: Build the Docker image
        run: docker build . --file Dockerfile --tag dbImage:$(date +%s)
      working-directory : ./words
        - uses: actions/checkout@v3
        - name: Build the Docker image
        run: docker build . --file Dockerfile --tag wordsImage:$(date +%s)

      


        

