name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: pull-request :
    types : [labeled]
jobs : 
  docker : 
    runs-on : ubuntu-latest
    steps :
      working-directory : ./web
      -
        name : webImage
        uses: docker/setup-buildx-action@v3
      -
      working-directory : ./db
      -
        name : dbImage
        uses: docker/setup-buildx-action@v3
      -
      working-directory : ./words
      -
        name : wordsImage
        uses : docker/setup-buildx-action@v3
      -
      


        

